---
- name: Print the detected package manager
  ansible.builtin.debug:
    msg: "{{ ansible_pkg_mgr }}"

# tasks file for lacework-agent-ansible-role
- name: add the lacework repo (yum/dnf)
  yum_repository:
    name: packages-lacework-prod
    description: packages-lacework-prod
    baseurl: https://packages.lacework.net/{{ lacework_release }}/RPMS/{{ ansible_architecture }}/
    gpgkey: https://packages.lacework.net/{{ lacework_release }}/keys/RPM-GPG-KEY-lacework
    gpgcheck: yes
    enabled: yes
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: add the lacework key (apt)
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: "EE0CC692"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: add the lacework repo (apt)
  apt_repository:
    repo: "deb [arch=amd64,arm64] https://packages.lacework.net/{{ lacework_release }}/DEB/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: lacework
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: install the lacework datacollector (apt/yum)
  package:
    name: lacework
    state: latest

- name: wait until /var/lib/lacework/config/ is created
  wait_for:
    path: /var/lib/lacework/config/

- name: generate config.json
  template:
    src: config.json.j2
    dest: /var/lib/lacework/config/config.json
    owner: root
    group: root
    mode: "0644"
  notify: restart lacework
