---
# tasks file for lacework-agent-ansible-role
- name: Print the detected package manager
  ansible.builtin.debug:
    msg: "{{ ansible_pkg_mgr }}"
    verbosity: 3

- include: install.yml
  when: lacework_state == "present"

- include: uninstall.yml
  when: lacework_state == "absent"
