---
# tasks file for lacework-agent-ansible-role
- name: add the lacework repo (yum)
  yum_repository:
    name: packages-lacework-prod
    description: packages-lacework-prod
    baseurl: https://packages.lacework.net/RPMS/x86_64/
    gpgkey: https://packages.lacework.net/keys/RPM-GPG-KEY-lacework
    gpgcheck: yes
    enabled: yes
  when: ansible_pkg_mgr == 'yum' and ansible_architecture == 'x86_64'

- name: add the lacework key (apt)
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "18E76630"
    state: present
  when: ansible_pkg_mgr == 'apt' and ansible_architecture == 'x86_64'

- name: add the lacework key (apt)
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "EE0CC692"
    state: present
  when: ansible_pkg_mgr == 'apt' and ansible_architecture == 'x86_64'

- name: add the lacework repo (apt)
  apt_repository:
    repo: "deb [arch=amd64] https://packages.lacework.net/DEB/{{ ansible_distribution | lower  }}/{{  ansible_distribution_version }} {{ ansible_distribution_release }} main"
    filename: lacework
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt' and ansible_architecture == 'x86_64'

- name: install the lacework datacollector (apt/yum)
  package:
    name: lacework
    state: latest
  when: ansible_architecture == 'x86_64'

- name: gather the package information
  package_facts:
    manager: auto
  when: ansible_architecture == 'aarch64'

- name: download lacework install.sh if 'lacework' not installed
  get_url:
    url: https://packages.lacework.net/install.sh
    dest: /tmp/lacework_install.sh
    mode: '0500'
  when: ansible_architecture == 'aarch64' and 'lacework' not in ansible_facts.packages

- name: install lacework datacollector (install.sh)
  command: sh /tmp/lacework_install.sh {{ lacework_accessToken }}
  when: ansible_architecture == 'aarch64' and 'lacework' not in ansible_facts.packages

- name: wait until /var/lib/lacework/config/ is created
  wait_for:
    path: /var/lib/lacework/config/

- name: generate config.json
  template:
    src: config.json.j2
    dest: /var/lib/lacework/config/config.json
    owner: root
    group: root
    mode: "0644"
