---
# remove package
- name: uninstall the lacework datacollector (apt/yum)
  ansible.builtin.package:
    name: lacework
    state: absent

# remove config files and logs
- name: remove lacework files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/lacework
    - /var/log/lacework

# remove repositorys and gpg keys
- name: remove the lacework repo (yum/dnf)
  ansible.builtin.yum_repository:
    name: packages-lacework-prod
    state: absent
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
  notify: yum-clean-metadata

- name: remove the lacework key (yum/dnf)
  ansible.builtin.rpm_key:
    key: https://packages.lacework.net/{{ lacework_release }}/keys/RPM-GPG-KEY-lacework
    state: absent
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: remove the lacework repo (apt)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64] https://packages.lacework.net/{{ lacework_release }}/DEB/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: lacework
    state: absent
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: remove the lacework key (apt)
  ansible.builtin.apt_key:
    id: "{{ lacework_apt_key_id }}"
    state: absent
  when: ansible_pkg_mgr == 'apt'
