---
# handlers file for lacework-agent-ansible-role
- name: restart lacework
  ansible.builtin.service:
    name: datacollector
    state: restarted

- name: yum-clean-metadata
  ansible.builtin.command: yum clean metadata
  args:
    warn: no