---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel-8-amd64
    image_owner: "309956199498"
    image_name: RHEL-8*HVM*-x86_64-*
    instance_type: t3.micro
    region: ${AWS_REGION}
    vpc_subnet_id: ${AWS_SUBNET_ID}
    tags:
      Name: molecule_rhel_instance_amd64
  - name: rhel-8-arm64
    image_owner: "309956199498"
    image_name: RHEL-8*HVM*-arm64-*
    instance_type: t4g.micro
    region: ${AWS_REGION}
    vpc_subnet_id: ${AWS_SUBNET_ID}
    tags:
      Name: molecule_rhel_instance_arm64
  - name: ubuntu-amd64
    image_owner: "099720109477"
    image_name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
    instance_type: t3.micro
    region: ${AWS_REGION}
    vpc_subnet_id: ${AWS_SUBNET_ID}
    tags:
      Name: molecule_ubuntu_instance_amd64
  - name: ubuntu-arm64
    image_owner: "099720109477"
    image_name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-*
    instance_type: t4g.micro
    region: ${AWS_REGION}
    vpc_subnet_id: ${AWS_SUBNET_ID}
    tags:
      Name: molecule_ubuntu_instance_arm64
provisioner:
  name: ansible
verifier:
  name: ansible
